name: Test FastAPI server

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests using pytest
        run: python -m pytest
